# Generated by Django 3.1.2 on 2020-10-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Html_Css_Javascript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('massage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Python_Django',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('massage', models.TextField()),
            ],
        ),
    ]
