# Generated by Django 3.1.2 on 2020-10-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_html_css_javascript_python_django'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python_Django',
            new_name='PythonandDjango',
        ),
    ]
